import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNav";
import { auth } from "@/auth";
import { getUserInfoForNav } from "@/app/actions/userActions";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Match Vault",
  description: "Generated by creator",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    shortcut: "/favicon.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user?.id || null;
  const isLoggedIn = Boolean(userId);

  // Don't rely on session.user.image here: with JWT sessions it won't change
  // until the token is refreshed (often only on re-login).
  const userInfo = userId ? await getUserInfoForNav() : null;

  const profileComplete = session?.user
    .profileComplete as boolean;
  const isAdmin = session?.user?.role === "ADMIN";
  return (
    <html lang="en">
      <body>
        <Providers profileComplete={profileComplete} userId={userId}>
          <div className="app-shell">
            <div className="app-panel overflow-hidden">
              <TopNav userInfo={userInfo} isLoggedIn={isLoggedIn} isAdmin={isAdmin} />
              <main>{children}</main>
            </div>
          </div>
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}