import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import Script from "next/script";
import TopNav from "@/components/navbar/TopNav";
import { auth } from "@/auth";
import { getUserInfoForNav } from "@/app/actions/userActions";

export const metadata: Metadata = {
  title: "Match Vault",
  description: "Generated by creator",
  icons: {
    icon: [{ url: "/favicon.png", type: "image/png" }],
    shortcut: "/favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user?.id || null;
  const isLoggedIn = Boolean(userId);

  // Don't rely on session.user.image here: with JWT sessions it won't change
  // until the token is refreshed (often only on re-login).
  const userInfo = userId ? await getUserInfoForNav() : null;

  const profileComplete = session?.user
    .profileComplete as boolean;
  const isAdmin = session?.user?.role === "ADMIN";
  return (
    <html lang="en">
      <body>
        <Script id="suppress-notallowed" strategy="beforeInteractive">{`(function(){
          try {
            var orig = console.error;
            console.error = function(){
              try {
                for (var i=0;i<arguments.length;i++){
                  var a = arguments[i];
                  var msg = "";
                  if (a && typeof a === 'object' && a.message) msg = String(a.message);
                  else msg = String(a);
                  if (msg.indexOf("The request is not allowed by the user agent")!==-1 || /not allowed by the user agent|not allowed by the platform/i.test(msg) || msg.indexOf("NotAllowedError")!==-1) {
                    try { window.dispatchEvent(new CustomEvent('screenShareNotAllowed', { detail: msg })); } catch(e){}
                    return;
                  }
                }
              } catch(e){}
              return orig.apply(console, arguments);
            };
            window.addEventListener('error', function(ev){
              try {
                var m = ev && ev.error && ev.error.message ? String(ev.error.message) : String(ev.message || '');
                if (/not allowed by the user agent|not allowed by the platform|NotAllowedError/i.test(m)){
                  try { window.dispatchEvent(new CustomEvent('screenShareNotAllowed', { detail: m })); } catch(e){}
                  ev.preventDefault();
                }
              } catch(e){}
            });
          } catch(e){}
        })();`}</Script>
        <Providers profileComplete={profileComplete} userId={userId}>
          <div className="app-shell">
            <div className="app-panel overflow-hidden">
              <TopNav userInfo={userInfo} isLoggedIn={isLoggedIn} isAdmin={isAdmin} />
              <main className="min-w-0 overflow-x-hidden">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}